apiVersion: v1
kind: Service
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  selector:
    app: k8s-doc-example
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort